apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: flame-gateway
  namespace: flame
spec:
  selector:
    istio: ingress # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "juny.me"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flame
  namespace: flame
spec:
  hosts:
  - "juny.me"
  gateways:
  - flame-gateway
  http:
  - route:
    - destination:
        host: flame
        port:
          number: 5005
