apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vaultwarden-gateway
  namespace: vaultwarden
spec:
  selector:
    istio: ingress # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "vault.juny.me"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vaultwarden
spec:
  hosts:
  - "vault.juny.me"
  gateways:
  - vaultwarden-gateway
  http:
  - match:
    - uri:
        exact: /notifications/hub
    route:
    - destination:
        host: vaultwarden
        port:
          number: 3012
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: vaultwarden
        port:
          number: 80
